### ISSUE TITLE
About 4.2

### ISSUE THREAD

**Issue by RoZhong** [jan9419/ORB_SLAM3_Monodepth#2]
Thanks for your great work.
 I have problems to understand part of 4.2.
just as  how to add Monodepth2 models in to pythonpath.
I also can't understand what the parameters in the command represent.
I really hope you can help. Thank you very much .

**Comment by jan9419** [comment]
After cloning the Monodepth2 repository (https://github.com/nianticlabs/monodepth2) to your local system, you can add it to the `PYTHONPATH` environment variable with the following command: 
`export PYTHONPATH=PATH_TO_CLONED_MONODEPTH_REPOSITORY`
 
The pre-trained Monodepth2 models used for the `input_encoder_path` and `input_decoder_path` arguments can be downloaded from: 
https://github.com/nianticlabs/monodepth2
The paths for the pre-trained Encoder and Decoder are then for example:
Encoder: `PATH_TO_MONODEPTH_PRETRAINED_MODEL/mono+stereo_1024x320/encoder.pth`
Decoder: `PATH_TO_MONODEPTH_PRETRAINED_MODEL/mono+stereo_1024x320/depth.pth`

After modifying the decoder file in your local Monodepth2 repository (`networks/depth_decoder.py`) as described in section 4.2, the pre-trained Monodepth2 models can be exported to TorchScript models.
